# Generated by Django 5.1 on 2024-08-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
