# Generated by Django 5.1 on 2024-08-20 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_scope_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='main',
        ),
        migrations.AddField(
            model_name='scope',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='articles.tag', verbose_name='Раздел'),
        ),
    ]
